#!/usr/bin/env python3
"""Plot FPS results generated by run_benchmark.py."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Tuple

import matplotlib.pyplot as plt
import pandas as pd


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path, help="CSV file with triangles,avg_fps columns")
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("data") / "fps_plot.png",
        help="Destination image path",
    )
    return parser.parse_args()


def load_data(path: Path) -> Tuple[pd.Series, pd.Series]:
    data = pd.read_csv(path)
    if "triangles" not in data or "avg_fps" not in data:
        raise ValueError("Input CSV must contain 'triangles' and 'avg_fps' columns")
    return data["triangles"], data["avg_fps"]


def plot(triangles: pd.Series, fps: pd.Series, output: Path) -> None:
    plt.figure(figsize=(6, 4))
    plt.plot(triangles, fps, marker="o", linewidth=2)
    plt.title("FPS vs Triangle Count")
    plt.xlabel("Triangle count")
    plt.ylabel("Average FPS")
    plt.grid(True, linestyle="--", alpha=0.4)
    plt.tight_layout()
    output.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(output)
    print(f"Saved plot to {output}")


def main() -> None:  # pragma: no cover - CLI utility
    args = parse_args()
    triangles, fps = load_data(args.input)
    plot(triangles, fps, args.output)


if __name__ == "__main__":
    main()
