#!/usr/bin/env python3
"""Plot CPU and GPU utilisation captured by run_benchmark.py."""

from __future__ import annotations

import argparse
import math

import numpy as np
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path, help="CSV file generated by run_benchmark.py")
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("data") / "resource_usage.png",
        help="Destination plot path",
    )
    parser.add_argument(
        "--textured",
        choices=["any", "yes", "no"],
        default="yes",
        help="Filter results by textured rendering (default: yes)",
    )
    parser.add_argument(
        "--lighting",
        type=str,
        default="",
        help="Optional comma-separated lighting modes to include",
    )
    return parser.parse_args()


def load_data(path: Path) -> pd.DataFrame:
    data = pd.read_csv(path)
    required = {
        "triangles",
        "lighting",
        "textured",
    }
    missing = required.difference(data.columns)
    if missing:
        raise ValueError(f"Input CSV is missing required columns: {', '.join(sorted(missing))}")

    data["triangles"] = data["triangles"].astype(int)
    data["lighting"] = data["lighting"].astype(str)
    data["textured"] = data["textured"].astype(str)

    numeric_columns = [
        "cpu_percent_mean",
        "process_cpu_percent_mean",
        "gpu_util_mean",
        "gpu_mem_util_mean",
        "gpu_mem_used_mb_mean",
        "gpu_temp_c_mean",
        "gpu_power_w_mean",
        "gpu_sm_clock_mhz_mean",
        "gpu_mem_clock_mhz_mean",
    ]

    for column in numeric_columns:
        if column not in data.columns:
            data[column] = float("nan")
        data[column] = pd.to_numeric(data[column], errors="coerce")
    return data


def filter_data(data: pd.DataFrame, textured: str, lighting: str) -> pd.DataFrame:
    if textured != "any":
        data = data[data["textured"].str.lower() == textured]
    if lighting:
        selected = {item.strip().lower() for item in lighting.split(",") if item.strip()}
        if selected:
            data = data[data["lighting"].str.lower().isin(selected)]
    return data


def plot(data: pd.DataFrame, output: Path, textured: str) -> None:
    grouped = data.groupby("lighting")
    if grouped.ngroups == 0:
        raise ValueError("No rows remain after applying the selected filters")

    metrics = [
        (
            "gpu_util_mean",
            "GPU Utilisation",
            "GPU utilisation (%)",
        ),
        (
            "gpu_mem_util_mean",
            "GPU Memory Utilisation",
            "Memory utilisation (%)",
        ),
        (
            "gpu_mem_used_mb_mean",
            "GPU Memory Used",
            "Memory used (MB)",
        ),
        (
            "gpu_temp_c_mean",
            "GPU Temperature",
            "Temperature (°C)",
        ),
        (
            "gpu_power_w_mean",
            "GPU Power",
            "Power draw (W)",
        ),
        (
            "gpu_sm_clock_mhz_mean",
            "GPU SM Clock",
            "Frequency (MHz)",
        ),
        (
            "gpu_mem_clock_mhz_mean",
            "GPU Memory Clock",
            "Frequency (MHz)",
        ),
    ]

    available_metrics = [item for item in metrics if data[item[0]].notna().any()]

    total_axes = 1 + len(available_metrics)
    cols = min(3, total_axes)
    rows = math.ceil(total_axes / cols)
    fig, axes = plt.subplots(rows, cols, figsize=(5.5 * cols, 4.0 * rows), sharex=True)
    if not isinstance(axes, (list, tuple, np.ndarray)):
        axes = [axes]
    else:
        axes = list(np.array(axes).reshape(-1))

    title_suffix = {
        "yes": "Textured",
        "no": "Untextured",
        "any": "All",
    }[textured]

    cpu_axis = axes[0]
    for lighting, group in grouped:
        group = group.sort_values("triangles")
        if group["cpu_percent_mean"].notna().any():
            cpu_axis.plot(
                group["triangles"],
                group["cpu_percent_mean"],
                marker="o",
                linewidth=2,
                label=f"{lighting} (system)",
            )
        if group["process_cpu_percent_mean"].notna().any():
            cpu_axis.plot(
                group["triangles"],
                group["process_cpu_percent_mean"],
                marker="x",
                linestyle="--",
                linewidth=1.5,
                label=f"{lighting} (process)",
            )

    cpu_axis.set_title(f"CPU Utilisation ({title_suffix})")
    cpu_axis.set_xlabel("Triangle count")
    cpu_axis.set_ylabel("CPU utilisation (%)")
    cpu_axis.grid(True, linestyle="--", alpha=0.4)
    cpu_axis.legend()

    for axis_index, (column, title, ylabel) in enumerate(available_metrics, start=1):
        axis = axes[axis_index]
        for lighting, group in grouped:
            group = group.sort_values("triangles")
            if group[column].notna().any():
                axis.plot(
                    group["triangles"],
                    group[column],
                    marker="o",
                    linewidth=2,
                    label=lighting,
                )
        axis.set_title(f"{title} ({title_suffix})")
        axis.set_xlabel("Triangle count")
        axis.set_ylabel(ylabel)
        axis.grid(True, linestyle="--", alpha=0.4)
        axis.legend()

    for axis in axes[total_axes:]:
        axis.remove()

    plt.tight_layout()
    output.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(output)
    print(f"Saved plot to {output}")


def main() -> None:  # pragma: no cover - CLI utility
    args = parse_args()
    data = load_data(args.input)
    filtered = filter_data(data, args.textured, args.lighting)
    plot(filtered, args.output, args.textured)


if __name__ == "__main__":
    main()
