#!/usr/bin/env python3
"""Plot CPU and GPU utilisation captured by run_benchmark.py."""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path, help="CSV file generated by run_benchmark.py")
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("data") / "resource_usage.png",
        help="Destination plot path",
    )
    parser.add_argument(
        "--textured",
        choices=["any", "yes", "no"],
        default="yes",
        help="Filter results by textured rendering (default: yes)",
    )
    parser.add_argument(
        "--lighting",
        type=str,
        default="",
        help="Optional comma-separated lighting modes to include",
    )
    return parser.parse_args()


def load_data(path: Path) -> pd.DataFrame:
    data = pd.read_csv(path)
    required = {
        "triangles",
        "lighting",
        "textured",
        "cpu_percent_mean",
        "process_cpu_percent_mean",
        "gpu_util_mean",
    }
    missing = required.difference(data.columns)
    if missing:
        raise ValueError(f"Input CSV is missing required columns: {', '.join(sorted(missing))}")

    data["triangles"] = data["triangles"].astype(int)
    data["lighting"] = data["lighting"].astype(str)
    data["textured"] = data["textured"].astype(str)
    for column in ["cpu_percent_mean", "process_cpu_percent_mean", "gpu_util_mean"]:
        data[column] = pd.to_numeric(data[column], errors="coerce")
    return data


def filter_data(data: pd.DataFrame, textured: str, lighting: str) -> pd.DataFrame:
    if textured != "any":
        data = data[data["textured"].str.lower() == textured]
    if lighting:
        selected = {item.strip().lower() for item in lighting.split(",") if item.strip()}
        if selected:
            data = data[data["lighting"].str.lower().isin(selected)]
    return data


def plot(data: pd.DataFrame, output: Path, textured: str) -> None:
    grouped = data.groupby("lighting")
    if grouped.ngroups == 0:
        raise ValueError("No rows remain after applying the selected filters")

    fig, axes = plt.subplots(1, 2, figsize=(11, 4.5), sharex=True)

    title_suffix = {
        "yes": "Textured",
        "no": "Untextured",
        "any": "All",
    }[textured]

    for lighting, group in grouped:
        group = group.sort_values("triangles")
        if group["cpu_percent_mean"].notna().any():
            axes[0].plot(
                group["triangles"],
                group["cpu_percent_mean"],
                marker="o",
                linewidth=2,
                label=f"{lighting} (system)",
            )
        if group["process_cpu_percent_mean"].notna().any():
            axes[0].plot(
                group["triangles"],
                group["process_cpu_percent_mean"],
                marker="x",
                linestyle="--",
                linewidth=1.5,
                label=f"{lighting} (process)",
            )
        if group["gpu_util_mean"].notna().any():
            axes[1].plot(
                group["triangles"],
                group["gpu_util_mean"],
                marker="o",
                linewidth=2,
                label=lighting,
            )

    axes[0].set_title(f"CPU Utilisation ({title_suffix})")
    axes[0].set_xlabel("Triangle count")
    axes[0].set_ylabel("CPU utilisation (%)")
    axes[0].grid(True, linestyle="--", alpha=0.4)
    axes[0].legend()

    axes[1].set_title(f"GPU Utilisation ({title_suffix})")
    axes[1].set_xlabel("Triangle count")
    axes[1].set_ylabel("GPU utilisation (%)")
    axes[1].grid(True, linestyle="--", alpha=0.4)
    axes[1].legend()

    plt.tight_layout()
    output.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(output)
    print(f"Saved plot to {output}")


def main() -> None:  # pragma: no cover - CLI utility
    args = parse_args()
    data = load_data(args.input)
    filtered = filter_data(data, args.textured, args.lighting)
    plot(filtered, args.output, args.textured)


if __name__ == "__main__":
    main()
