#!/usr/bin/env python3
"""Plot FPS results generated by run_benchmark.py."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Tuple

import matplotlib.pyplot as plt
import pandas as pd


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path, help="CSV file generated by run_benchmark.py")
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("data") / "fps_plot.png",
        help="Destination image path",
    )
    parser.add_argument(
        "--textured",
        choices=["any", "yes", "no"],
        default="yes",
        help="Filter results by textured rendering (default: yes)",
    )
    parser.add_argument(
        "--lighting",
        type=str,
        default="",
        help="Optional comma-separated lighting modes to include",
    )
    return parser.parse_args()


def load_data(path: Path) -> pd.DataFrame:
    data = pd.read_csv(path)
    required = {"triangles", "avg_fps", "lighting", "textured"}
    missing = required.difference(data.columns)
    if missing:
        raise ValueError(f"Input CSV is missing required columns: {', '.join(sorted(missing))}")
    data["triangles"] = data["triangles"].astype(int)
    data["avg_fps"] = data["avg_fps"].astype(float)
    data["lighting"] = data["lighting"].astype(str)
    data["textured"] = data["textured"].astype(str)
    return data


def filter_data(data: pd.DataFrame, textured: str, lighting: str) -> pd.DataFrame:
    if textured != "any":
        data = data[data["textured"].str.lower() == textured]
    if lighting:
        selected = {item.strip().lower() for item in lighting.split(",") if item.strip()}
        if selected:
            data = data[data["lighting"].str.lower().isin(selected)]
    return data


def plot(data: pd.DataFrame, output: Path, textured: str) -> None:
    plt.figure(figsize=(7, 4.5))
    grouped = data.groupby("lighting")
    if grouped.ngroups == 0:
        raise ValueError("No rows remain after applying the selected filters")

    for lighting, group in grouped:
        group = group.sort_values("triangles")
        plt.plot(group["triangles"], group["avg_fps"], marker="o", linewidth=2, label=lighting)

    title_suffix = {
        "yes": "Textured",
        "no": "Untextured",
        "any": "All",
    }[textured]
    plt.title(f"FPS vs Triangle Count ({title_suffix})")
    plt.xlabel("Triangle count")
    plt.ylabel("Average FPS")
    plt.grid(True, linestyle="--", alpha=0.4)
    plt.legend(title="Lighting")
    plt.tight_layout()
    output.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(output)
    print(f"Saved plot to {output}")


def main() -> None:  # pragma: no cover - CLI utility
    args = parse_args()
    data = load_data(args.input)
    filtered = filter_data(data, args.textured, args.lighting)
    plot(filtered, args.output, args.textured)


if __name__ == "__main__":
    main()
